{% set name = "policy_sentry" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/policy_sentry-{{ version }}.tar.gz
  sha256: 8b88cb58a390ae7e0e06db13b3bbb5ece0d32d7d7c38a92259eb9c4722198fb5

build:
  number: 0
  noarch: python
  entry_points:
    - policy_sentry=policy_sentry.bin.cli:main
  script: {{ PYTHON }} -m pip install . -vv

test:
  imports:
    - policy_sentry
    - policy_sentry.analysis
  commands:
    - pip check
    - policy_sentry --help
  requires:
    - pip

about:
  home: https://github.com/salesforce/policy_sentry
  summary: Generate locked-down AWS IAM Policies
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ForgottenProgramme
