{% set name = "https://github.com/bojiang/typing_utils" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bojiang/typing_utils/archive/v0.1.0.tar.gz
  sha256: d0e8b3019b990bd64b0f9d0ee0b327fb77ca036073fe837a1dc0cd71d007bf3d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - typing_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bojiang/typing_utils
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ForgottenProgramme
