{% set name = "https://www.github.com/conda-incubator/grayskull" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python
  entry_points:
    - grayskull = grayskull.__main__:main
    - greyskull = grayskull.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

test:
  imports:
    - grayskull
    - grayskull.base
  commands:
    - pip check
    - grayskull --help
    - greyskull --help
  requires:
    - pip

about:
  home: https://github.com/conda-incubator/grayskull
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ForgottenProgramme
