{% set name = "https://www.github.com/conda-incubator/grayskull" %}
{% set version = "0.8.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.github.com/conda-incubator/grayskull/archive/0.8.5.tar.gz
  sha256: ba8d7806a44cda2c7845a7557b8ca5ba412cd59f67ec7d06d1a2c8fcaeabc8bd

build:
  number: 0
  noarch: python
  entry_points:
    - grayskull = grayskull.__main__:main
    - greyskull = grayskull.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=30.3.0
    - setuptools-scm
  run:
    - colorama
    - pip
    - progressbar2 >=3.53.0
    - python >=3.7
    - rapidfuzz >=0.7.6,<0.13.0
    - requests
    - ruamel.yaml >=0.16.10
    - ruamel.yaml.jinja2
    - setuptools >=30.3.0
    - stdlib-list

test:
  imports:
    - grayskull
    - grayskull.base
  commands:
    - pip check
    - grayskull --help
    - greyskull --help
  requires:
    - pip

about:
  home: https://github.com/conda-incubator/grayskull
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ForgottenProgramme
