{% set name = "https://github.com/conda-incubator/ensureconda" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python
  entry_points:
    - ensureconda = ensureconda.cli:ensureconda_cli
  script: {{ PYTHON }} -m pip install . -vv

test:
  imports:
    - ensureconda
  commands:
    - pip check
    - ensureconda --help
  requires:
    - pip

about:
  home: https://github.com/conda-incubator/ensureconda
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - ForgottenProgramme
